# Configuración para desarrollo local apuntando a VM en Google Cloud
# mongu:
#   uri: "mongodb://34.39.160.195:27017"
#   database: "iot_db"

# influxdb:
#   url: "http://34.39.160.195:8086"
#   token: "my-super-token"
#   org: "my-org"
#   bucket: "sensores"

server:
  port: "8090"

# Configuración para contenedores Docker
mongu:
  uri: "mongodb://mongu:27017"
  database: "iot_db"
influxdb:
  url: "http://influxdb:8086"
  token: "my-super-token"
  org: "my-org"
  bucket: "sensores"

# Configuración de monitoreo de sensores
sensor:
  timeout_minutes: 5  # Tiempo en minutos para considerar un sensor desconectado

# Configuración de notificaciones (opcional)
notification:
  url: "http://notification-service:8091/sensor/alert"  # URL del servicio de notificaciones