postgres:
  host: "gestion-db"
  port: 5432
  user: "gestion_user"
  password: "gestion_pass"
  dbname: "gestion_db"
  sslmode: "disable"

server:
  port: "8092"

services:
  parser_url: "http://iot-service:8090"
  base_url: "https://anita-submicroscopic-overgently.ngrok-free.app"
