postgres:
  host: "localhost"
  port: 5433
  user: "gestion_user"
  password: "gestion_pass"
  dbname: "gestion_db"
  sslmode: "disable"

server:
  port: "8092"

services:
  parser_url: "http://localhost:8090"
  base_url: "https://interbanded-kole-sneeringly.ngrok-free.app"

# Para conexión externa (cuando esté en Google Cloud)
# postgres:
#   host: "34.39.160.195"
#   port: 5432
#   user: "gestion_user"
#   password: "gestion_pass"
#   dbname: "gestion_db"
#   sslmode: "disable"
