export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    inicio: '/dashboard',
    formulario: '/dashboard/formulario',
    gestion: '/dashboard/gestion',
    solicitudes: '/dashboard/solicitudes',
    account: '/dashboard/account',
    alertas: '/dashboard/alertas',
    activos: '/dashboard/activos',
    reporteFallas: '/dashboard/reporte-fallas',
    sensores: '/dashboard/sensores',
    reportesTecnicos: '/dashboard/reportes-tecnicos',
    planos: '/errors/not-found',
    contactos: '/dashboard/contactos',
    graficos: '/dashboard/graficos',
    ml: '/dashboard/prediccion',
    settings: '/dashboard/settings',
    activoDetail: (id: string) => `/dashboard/activos/${id}`,
    agregarDatos: (tipo: string) => `/dashboard/agregar-datos/${tipo}`,
  },
  errors: { notFound: '/errors/not-found' },
} as const;
